baseURL = "https://g1uke.github.io/"
title = "Максим Ведерник @g1uke"
theme = "g1"

enableRobotsTXT = true
googleAnalytics = "G-6J1PVGJXMX"
disqusShortname = 'g1uke'

[Taxonomies]
    # tag = "tags"
    # category = "categories"

[minify]
  minifyOutput = true

[menu]
  # [[menu.main]]
  #   identifier = "works"
  #   name = "Работы"
  #   url = "/works"
  #   weight = 10

  # [[menu.main]]

  #   name = "Записи"
  #   url = "/posts"
  #   weight = 20

  [[menu.main]]
    identifier = "contacts"
    name = "Контакты"
    url = "/contacts"
    weight = 30

[params]
  sitebrand = "g1uke.github.io"
  description = "Web Design, HTML, CSS, JS, PHP, Python"
  yandexmetrika = true
  telegramcomments = "WvouaWlt"
  ogimg = "images/ogimg.jpg"
  [[params.social]]
    icon = "g1con__envelope"
    name = "Email"
    url = "mailto:g1uke@pm.me"
    weight = 10

  [[params.social]]
    icon = "g1con__telegram"
    name = "Telegram"
    url = "https://t.me/g1uke"
    target = "_blank"
    weight = 20
  
  [[params.social]]
    icon = "g1con__discord"
    name = "Discord - g1uke"
    url = "https://discord.gg/YQHR2KX"
    target = "_blank"
    weight = 50